title: Travel
description: "Social Media for Del Norte High School"
owner_name: Kiruthic Selvakumar
github_username: Kiruthic-Selvakumar
github_repo: "travel_frontend" 
baseurl: "/travel_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/travel/destination_imagination/destination_main.md
  - navigation/travel/cuisine_chronicles/cuisine_main.md
  - navigation/travel/budget_brilliance/budget_main.md
  - navigation/travel/fair_fares/fair_main.md
  - navigation/travel/lodging_listings/lodging_main.md
  - navigation/travel/packing_portal/packing_main.md
  - navigation/travel/wellness_waypoints/wellness_main.md